title: Darsh's Rad Stuff
description: My personal site
theme: just-the-docs
color_scheme: darshsrad

url: https://www.darshsrad.com

markdown: kramdown
kramdown:
  math_engine: katex

include:
  - generated

exclude:
  - CNAME
  - README.md
